-keep class com.amap.api.location.** { *; }
-keep class com.amap.api.fence.** { *; }
-keep class com.amap.api.maps.** { *; }
-keep class com.amap.api.mapcore.** { *; }
-keep class com.amap.api.services.** { *; }
-keep class com.amap.apis.utils.core.** { *; }
-keep class com.autonavi.** { *; }
-keep class com.loc.** { *; }
-dontwarn com.amap.**
